#!/bin/bash

# Auto-Build Environment Setup for Better Auth Implementation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/mariogalla/development/augenblick"

cd "$PROJECT_DIR"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PREREQUISITE CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check for pnpm
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm is not installed. Please install it first.${NC}"
    exit 1
fi
echo -e "${GREEN}pnpm found${NC}"

# Check for required env vars
if [ -z "$DATABASE_URL" ] && ! grep -q "DATABASE_URL" "$PROJECT_DIR/.env" 2>/dev/null; then
    echo -e "${RED}DATABASE_URL not found in .env file${NC}"
    exit 1
fi
echo -e "${GREEN}DATABASE_URL configured${NC}"

# Check for BETTER_AUTH_SECRET (may not exist yet for initial setup)
if ! grep -q "BETTER_AUTH_SECRET" "$PROJECT_DIR/.env" 2>/dev/null; then
    echo -e "${YELLOW}BETTER_AUTH_SECRET not found - will need to be added during setup${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
pnpm dev &
wait_for_service 3000 "Next.js App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js App:  http://localhost:3000"
echo "  Login Page:   http://localhost:3000/login"
echo "  Admin Office: http://localhost:3000/office"
echo ""
echo "Development Commands:"
echo "  pnpm dev          - Start development server"
echo "  pnpm build        - Build for production"
echo "  pnpm lint         - Run ESLint"
echo "  npx drizzle-kit push - Push database schema"
echo ""
echo "Auth Setup Commands (run once):"
echo "  npx @better-auth/cli generate --output ./src/lib/db/schema/auth.ts"
echo "  npx tsx scripts/seed-admin.ts"
echo ""
