#!/bin/bash

# Auto-Build Environment Setup
# Spec: 003 - Upgrade Tailwind CSS v3 to v4 with shadcn/ui
# Generated by Planner Agent

set -e

echo "========================================"
echo "Tailwind v4 Upgrade - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/mariogalla/development/augenblick"
cd "$PROJECT_DIR"

# Check Node.js version
echo ""
echo "Checking Node.js version..."
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}Error: Node.js 20+ required. Current: $(node -v)${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js version OK: $(node -v)${NC}"

# Check pnpm
echo ""
echo "Checking pnpm..."
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}Error: pnpm not found${NC}"
    exit 1
fi
echo -e "${GREEN}pnpm found: $(pnpm -v)${NC}"

# Install dependencies
echo ""
echo "Installing dependencies..."
pnpm install

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "========================================"
echo "Starting Development Server"
echo "========================================"

# Start Next.js dev server
pnpm dev &
DEV_PID=$!

# Wait for server to be ready
wait_for_service 3000 "Next.js Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js Dev: http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Dev Server: $DEV_PID"
echo ""
echo "To stop the server:"
echo "  kill $DEV_PID"
echo ""
echo "Current Tailwind version:"
pnpm list tailwindcss 2>/dev/null || echo "  Not yet installed"
echo ""
