#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001 - Configure Neon Database for Serverless Deployment

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/mariogalla/development/augenblick"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking required dependencies..."

cd "$PROJECT_DIR"

# Check if pnpm is installed
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm is not installed. Please install it first.${NC}"
    exit 1
fi

# Check if node is the right version
NODE_VERSION=$(node --version)
echo -e "${GREEN}Node.js version: $NODE_VERSION${NC}"

# Install dependencies if node_modules doesn't exist or is outdated
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    pnpm install
fi

# ============================================
# CHECK ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Checking environment variables..."

if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file not found${NC}"
    echo "Creating .env from .env.example..."
    cp .env.example .env
    echo -e "${YELLOW}Please configure your environment variables in .env${NC}"
fi

# Check for DATABASE_URL (will be added by this task)
if grep -q "DATABASE_URL" .env 2>/dev/null; then
    echo -e "${GREEN}DATABASE_URL found in .env${NC}"
else
    echo -e "${YELLOW}DATABASE_URL not configured yet${NC}"
    echo "You'll need to add your Neon database connection string after setup."
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js dev server
pnpm dev &
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Database Commands (after DATABASE_URL is configured):"
echo "  pnpm drizzle-kit generate  - Generate migrations"
echo "  pnpm drizzle-kit migrate   - Apply migrations"
echo "  pnpm drizzle-kit push      - Push schema (dev only)"
echo "  pnpm drizzle-kit studio    - Open database GUI"
echo ""
echo "To stop: Press Ctrl+C"
echo ""
