#!/bin/bash

# Auto-Build Environment Setup
# Spec: 006 - Service Layer with neverthrow Error Handling
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 006: Service Layer Implementation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/Users/mariogalla/development/augenblick"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

cd "$PROJECT_DIR"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    pnpm install
fi

# Check for required new dependencies
if ! pnpm list neverthrow 2>/dev/null | grep -q neverthrow; then
    echo -e "${YELLOW}Installing neverthrow...${NC}"
    pnpm add neverthrow
fi

if ! pnpm list pdfkit 2>/dev/null | grep -q pdfkit; then
    echo -e "${YELLOW}Installing pdfkit...${NC}"
    pnpm add pdfkit
    pnpm add -D @types/pdfkit
fi

if ! pnpm list @paralleldrive/cuid2 2>/dev/null | grep -q cuid2; then
    echo -e "${YELLOW}Installing @paralleldrive/cuid2...${NC}"
    pnpm add @paralleldrive/cuid2
fi

echo -e "${GREEN}Dependencies ready${NC}"

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "Checking environment..."

if [ ! -f ".env" ]; then
    echo -e "${RED}.env file not found!${NC}"
    echo "Copy .env.example to .env and configure:"
    echo "  cp .env.example .env"
    exit 1
fi

# Check DATABASE_URL
if ! grep -q "DATABASE_URL" .env; then
    echo -e "${RED}DATABASE_URL not configured in .env${NC}"
    exit 1
fi

echo -e "${GREEN}Environment ready${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

cd "$PROJECT_DIR"
npm run dev &
NEXT_PID=$!

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Development:"
echo "  - Edit files in src/lib/services/"
echo "  - Server Actions in src/app/actions/"
echo "  - Schema files in src/lib/db/schema/"
echo ""
echo "Commands:"
echo "  pnpm run dev      - Start dev server"
echo "  pnpm run lint     - Run ESLint"
echo "  npx tsc --noEmit  - Type check"
echo ""
echo "To stop: kill $NEXT_PID"
echo ""
