#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 005
# Cosmetics Studio Database Schema Implementation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/mariogalla/development/augenblick"
cd "$PROJECT_ROOT"

echo ""
echo "Project: Augenblick Kosmetikstudio"
echo "Task: Database Schema Implementation"
echo ""

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo "Installing dependencies..."

# Check if cuid2 is installed
if ! grep -q "@paralleldrive/cuid2" package.json 2>/dev/null; then
    echo -e "${YELLOW}Installing @paralleldrive/cuid2...${NC}"
    pnpm add @paralleldrive/cuid2
else
    echo -e "${GREEN}@paralleldrive/cuid2 already installed${NC}"
fi

# Check if drizzle-kit is installed (dev dependency)
if ! grep -q "drizzle-kit" package.json 2>/dev/null; then
    echo -e "${YELLOW}Installing drizzle-kit...${NC}"
    pnpm add -D drizzle-kit
else
    echo -e "${GREEN}drizzle-kit already installed${NC}"
fi

echo ""
echo -e "${GREEN}Dependencies ready!${NC}"

# ============================================
# VERIFY SCHEMA DIRECTORY
# ============================================

SCHEMA_DIR="src/lib/db/schema"

echo ""
echo "Verifying schema directory..."

if [ -d "$SCHEMA_DIR" ]; then
    echo -e "${GREEN}Schema directory exists: $SCHEMA_DIR${NC}"
    echo "Current schema files:"
    ls -la "$SCHEMA_DIR"
else
    echo -e "${YELLOW}Creating schema directory: $SCHEMA_DIR${NC}"
    mkdir -p "$SCHEMA_DIR"
fi

# ============================================
# VERIFY DRIZZLE CONFIG
# ============================================

echo ""
echo "Verifying Drizzle configuration..."

if [ -f "drizzle.config.ts" ]; then
    echo -e "${GREEN}drizzle.config.ts exists${NC}"
else
    echo -e "${RED}WARNING: drizzle.config.ts not found!${NC}"
    echo "You may need to create it manually"
fi

# ============================================
# CHECK AUTH SCHEMA AVAILABILITY
# ============================================

echo ""
echo "Checking auth schema availability..."

AUTH_SCHEMA="$SCHEMA_DIR/auth.ts"
AUTH_SCHEMA_WORKTREE=".worktrees/004-implement-better-auth-with-email-password-for-sing/src/lib/db/schema/auth.ts"

if [ -f "$AUTH_SCHEMA" ]; then
    echo -e "${GREEN}auth.ts exists in schema directory${NC}"
elif [ -f "$AUTH_SCHEMA_WORKTREE" ]; then
    echo -e "${YELLOW}auth.ts available in worktree 004${NC}"
    echo "Can be copied with: cp $AUTH_SCHEMA_WORKTREE $AUTH_SCHEMA"
else
    echo -e "${RED}WARNING: auth.ts not found!${NC}"
    echo "customer-audit.ts requires the user table from auth.ts"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Ensure auth.ts exists (copy from worktree if needed)"
echo "  2. Create schema files: customers.ts, gdpr-versions.ts, etc."
echo "  3. Run: npx tsc --noEmit (to verify types)"
echo "  4. Run: npx drizzle-kit generate (to create migrations)"
echo ""
echo "Schema location: $SCHEMA_DIR"
echo ""
echo "Commands:"
echo "  npm run dev          - Start development server"
echo "  npx tsc --noEmit     - Type check"
echo "  npx drizzle-kit generate - Generate migrations"
echo "  npx drizzle-kit push     - Push to database (dev)"
echo ""
