#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Next.js 15 App Router Migration

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Next.js 15 App Router Migration"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/mariogalla/development/augenblick"
cd "$PROJECT_ROOT"

# Check for pnpm
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm is not installed. Please install it first.${NC}"
    exit 1
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
pnpm dev &
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Pages to verify after migration:"
echo "  - Home:                  http://localhost:3000/"
echo "  - Lashlift:              http://localhost:3000/lashlift"
echo "  - Lashextension 1:1:     http://localhost:3000/lashextension-1-zu-1-technik"
echo "  - Lashextension Volumen: http://localhost:3000/lashextension-volumentechnik"
echo "  - Impressum:             http://localhost:3000/impressum"
echo "  - Datenschutz:           http://localhost:3000/datenschutz"
echo "  - 404:                   http://localhost:3000/nonexistent"
echo ""
echo "API Routes to test:"
echo "  - Newsletter: POST http://localhost:3000/api/newsletter"
echo "  - Email:      POST http://localhost:3000/api/email"
echo ""
echo "To stop: Press Ctrl+C"
echo ""
