#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 008
# Mobile-Friendly Customer Signature Management System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 008 - Customer Signature Management"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project Directory
PROJECT_DIR="/Users/mariogalla/development/augenblick"
cd "$PROJECT_DIR"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
else
    echo -e "${GREEN}node_modules exists${NC}"
fi

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment variables..."

# Check for .env file
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        echo -e "${YELLOW}No .env file found. Copying from .env.example${NC}"
        cp .env.example .env
    else
        echo -e "${RED}No .env file found and no .env.example to copy${NC}"
        exit 1
    fi
fi

# Check DATABASE_URL
if ! grep -q "DATABASE_URL" .env; then
    echo -e "${RED}DATABASE_URL not found in .env${NC}"
    exit 1
fi
echo -e "${GREEN}DATABASE_URL configured${NC}"

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."

# Kill any existing process on port 3000
lsof -ti:3000 | xargs kill -9 2>/dev/null || true

# Start Next.js in background
npm run dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Routes:"
echo "  Customer List:     http://localhost:3000/office/kunden"
echo "  New Customer:      http://localhost:3000/office/kunden/neu"
echo "  GDPR Management:   http://localhost:3000/office/datenschutz"
echo ""
echo "Process IDs:"
echo "  Next.js: $NEXT_PID"
echo ""
echo "To stop all services: kill $NEXT_PID"
echo ""
